name: md_picture_migrate_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/CaiJingLong/md_picture_migrate_cli
# publish_to: https://pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  dio: ^5.1.0
  http: ^0.13.5

executables:
  mdm: 
