name: Add binaries to release
run-name: Add binaries to release ${{ github.event.release.tag_name }}
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  release:
    types:
      - created

jobs:
  upload:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    name: Upload ${{ matrix.os }} binaries to release ${{ github.event.release.tag_name }}
    steps:
      - name: Upload
        uses: caijinglong/action-dart-compile@v1
